apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-application
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 3
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: ereta19/argocdproject:1.1
        ports:
        - containerPort: 8080
